#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Test Nueva Clase - Generated by ADAI Class Builder
Clase de prueba con sistema de progreso integrado
"""

import cv2
import numpy as np
import time
import os
import sys

# Agregar el directorio padre al path para importar el reporter
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(os.path.dirname(current_dir))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

try:
    from class_progress_reporter import create_progress_reporter
    PROGRESS_AVAILABLE = True
except ImportError:
    PROGRESS_AVAILABLE = False
    print("⚠️ Progress Reporter no disponible")

try:
    from services.esp32_services.esp32_client import get_esp32_client, connect_to_esp32
    ESP32_AVAILABLE = True
except ImportError:
    ESP32_AVAILABLE = False
    print("⚠️ ESP32 Client no disponible")

class TestNuevaClase:
    def __init__(self):
        print("🎓 Test Nueva Clase iniciada")
        
        # Crear reporter de progreso
        if PROGRESS_AVAILABLE:
            self.reporter = create_progress_reporter("test_nueva_clase", "default", 5)
        else:
            self.reporter = None
            print("⚠️ Ejecutando sin sistema de progreso")
        
        # Conectar al ESP32 si está disponible
        self.esp32_client = None
        if ESP32_AVAILABLE:
            try:
                print("🔌 Conectando al ESP32...")
                if connect_to_esp32():
                    self.esp32_client = get_esp32_client()
                    print("✅ Conectado al ESP32")
                else:
                    print("⚠️ No se pudo conectar al ESP32")
            except Exception as e:
                print(f"❌ Error conectando al ESP32: {e}")
        else:
            print("⚠️ Ejecutando sin conexión ESP32")
        
    def run(self):
        """Ejecutar la clase con reporte de progreso"""
        try:
            print("🚀 Ejecutando test nueva clase...")
            
            # Fase 1: Introducción
            if self.reporter:
                self.reporter.start_phase("class_intro", "Iniciando clase de prueba", "Preparando el entorno de trabajo")
            else:
                print("📚 Fase: Introducción - Iniciando clase de prueba")
            
            time.sleep(1)
            
            # Actualizar progreso
            if self.reporter:
                self.reporter.update_progress("Configuración inicial", "Verificando dependencias")
            else:
                print("📊 Progreso: Configuración inicial - Verificando dependencias")
            
            time.sleep(1)
            
            # Fase 2: Presentación Teórica
            if self.reporter:
                self.reporter.complete_phase("theory_presentation", "Conceptos fundamentales", "Explicando teoría básica")
            else:
                print("📚 Fase: Presentación Teórica - Conceptos fundamentales")
            
            time.sleep(1)
            
            # Actualizar progreso en teoría
            if self.reporter:
                self.reporter.update_progress("Definiciones", "Estableciendo conceptos clave")
            else:
                print("📊 Progreso: Definiciones - Estableciendo conceptos clave")
            
            time.sleep(1)
            
            # Fase 3: Demostración Práctica
            if self.reporter:
                self.reporter.complete_phase("practical_demo", "Ejemplos prácticos", "Mostrando aplicaciones reales")
            else:
                print("📚 Fase: Demostración Práctica - Ejemplos prácticos")
            
            # Enviar comandos ESP32 si está disponible
            if self.esp32_client and self.esp32_client.is_connected():
                print("🤖 Enviando comandos al ESP32...")
                
                # Saludo con gesto
                if self.esp32_client.send_gesture('wave', {'intensity': 0.8}, 2.0):
                    print("✅ Gesto de saludo enviado")
                
                # Mensaje de bienvenida
                if self.esp32_client.send_speech("¡Hola! Bienvenidos a la clase de prueba"):
                    print("✅ Mensaje de bienvenida enviado")
                
                # Movimiento de brazo
                coordinates = {'x': 0, 'y': 45, 'z': 90}
                if self.esp32_client.send_movement('arm', coordinates, 1.5):
                    print("✅ Movimiento de brazo enviado")
            
            time.sleep(1)
            
            # Actualizar progreso en práctica
            if self.reporter:
                self.reporter.update_progress("Simulación", "Ejecutando ejemplos")
            else:
                print("📊 Progreso: Simulación - Ejecutando ejemplos")
            
            time.sleep(1)
            
            # Fase 4: Sesión Interactiva
            if self.reporter:
                self.reporter.complete_phase("interactive_session", "Preguntas y respuestas", "Interactuando con el usuario")
            else:
                print("📚 Fase: Sesión Interactiva - Preguntas y respuestas")
            
            time.sleep(1)
            
            # Fase 5: Evaluación Final
            if self.reporter:
                self.reporter.complete_phase("final_exam", "Evaluación", "Verificando comprensión")
            else:
                print("📚 Fase: Evaluación Final - Evaluación")
            
            time.sleep(1)
            
            # Completar clase
            if self.reporter:
                self.reporter.complete_class("Test Nueva Clase completada exitosamente")
            else:
                print("🎉 Test Nueva Clase completada exitosamente")
            
            # Mostrar progreso final
            if self.reporter:
                progress_info = self.reporter.get_progress_info()
                print(f"📊 Progreso final: {progress_info.get('progress_percentage', 0)}% - {progress_info.get('current_phase', 'Completada')}")
            
        except Exception as e:
            error_msg = f"Error ejecutando clase: {e}"
            print(f"❌ {error_msg}")
            
            if self.reporter:
                self.reporter.error_in_class(error_msg)

if __name__ == "__main__":
    clase = TestNuevaClase()
    clase.run()
